csv_files:
  - file_path: "../../data/games_detailed_info2025.csv"
    csv_columns:
      - "id"
      - "name"
      - "description"
    table_name: "games"
    table_columns:
      - "bgg_id"
      - "name"
      - "description"
  - file_path: "../../data/bgg-26m-reviews.csv"
    csv_columns:
      - "user"
      - "rating"
      - "comment"
      - "ID"
    table_name: "comments"
    table_columns:
      - "user"
      - "rating"
      - "comment"
      - "game_id"
