database_connection:
  user: ljiang
  host: localhost
  port: 5432
  database: bgg

csv_files:
  - file_path: "data/games_detailed_info2025.csv"
    csv_columns:
      - "id"
      - "name"
      - "description"
    table_name: "games"
    table_columns:
      - "bgg_id"
      - "name"
      - "description"
  - file_path: "data/splits"
    csv_columns:
      - "user"
      - "rating"
      - "comment"
      - "ID"
    table_name: "comments"
    table_columns:
      - "user"
      - "rating"
      - "comment"
      - "game_id"

data_preprocessing:
  test_size: 0.2
  random_state: 42
  output_dir: /tmp/data