experiment_name: "bert-bgg-comment-score-predictor"
model_name: "distilbert/distilbert-base-uncased"
tokenizer_path: "distilbert/distilbert-base-uncased"
train_data_path: "/tmp/data/train.dataset"
val_data_path: "/tmp/data/eval.dataset"
output_dir: "models/checkpoints/bert-finetuned"
num_labels: 2  # Binary classification
batch_size: 16
learning_rate: 2e-5
epochs: 3
warmup_steps: 100